# Generated by Django 3.0.4 on 2020-08-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_email', models.EmailField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=255)),
                ('t_email', models.EmailField(max_length=150)),
            ],
        ),
    ]
