# Generated by Django 3.0.4 on 2020-08-26 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='t_contact',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='In the format +999999999999', regex='^\\+?1?\\d{10,12}$')]),
        ),
        migrations.AddField(
            model_name='form2',
            name='t_subject',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
