# Generated by Django 3.0.4 on 2020-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200826_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='c_email',
            field=models.EmailField(blank=True, max_length=150, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='form1',
            name='c_name',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
    ]
